version: "3"

services:
    mav_ipp_sim:
        build: .
        volumes:
            - ${REPO_DIR}:/mav_ipp
        environment:
            - REPO_DIR=${REPO_DIR}
            - GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}
        command: "sleep 5h"
    